# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    conditionalasset.twig_extension:
        class: AppBundle\Twig\ConditionalAssetExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name : twig.extension }
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments:
            router: "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }